spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_service
    username: postgres
    password: R2-D2-F1-L1

app:
  user-url: http://localhost:89/internal/user
  library-url: http://localhost:92/internal/library

server:
  port: 90
