spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: book-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: book-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://book-db:5432/book-service
    username: root
    password: root

app:
  user-url: http://user-service:8080/internal/user
  library-url: http://library-service:8080/internal/library

server:
  port: 8080

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: LibraryService

