spring:
  application:
    name: user-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: user_service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://user-db:5432/user-service
    username: root
    password: root

server:
  port: 8080

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: LibraryService

